from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from backend.models.enums import AgentStatus


class AgentResponse(BaseModel):
    """Standard response returned by AI agents."""

    model_config = ConfigDict(
        extra="ignore",
        str_strip_whitespace=True,
    )

    status: AgentStatus = Field(
        ...,
        description="Execution status of the agent.",
    )

    message: str = Field(
        ...,
        min_length=1,
        description="Human-readable response message.",
    )

    data: Any = Field(
        default=None,
        description="Structured output generated by the agent.",
    )

    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Time when the response was generated.",
    )