from pydantic import BaseModel, ConfigDict, Field

from backend.models.news import NewsArticle
from backend.models.risk import RiskAnalysis


class NewsAgentInput(BaseModel):
    """Input provided to the News Intelligence Agent."""

    model_config = ConfigDict(
        extra="ignore",
        str_strip_whitespace=True,
    )

    query: str = Field(
        ...,
        min_length=1,
        description="Search query.",
    )

    max_results: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Maximum number of search results.",
    )


class StructuredNews(BaseModel):
    """Structured output produced by the News Intelligence Agent."""

    model_config = ConfigDict(extra="ignore")

    query: str

    articles: list[NewsArticle] = Field(
        default_factory=list,
        description="Processed news articles.",
    )

    article_count: int = Field(
        default=0,
        ge=0,
    )


class RiskAgentInput(BaseModel):
    """Input provided to the Risk Classification Agent."""

    model_config = ConfigDict(extra="ignore")

    articles: list[NewsArticle] = Field(
        default_factory=list,
    )


class RiskAgentOutput(BaseModel):
    """Output generated by the Risk Classification Agent."""

    model_config = ConfigDict(extra="ignore")

    analyses: list[RiskAnalysis] = Field(
        default_factory=list,
    )