from pydantic import BaseModel, ConfigDict, Field


class ExecutiveSummary(BaseModel):
    """Executive summary generated by the Executive Summary Agent."""

    model_config = ConfigDict(
        extra="ignore",
        str_strip_whitespace=True,
    )

    summaries: list[str] = Field(
        default_factory=list,
        description="List of generated executive summaries.",
    )
