from fastapi import APIRouter

router = APIRouter(
    prefix="/api/news",
    tags=["News Intelligence"],
)


@router.get("")
async def get_news_intelligence():
    return {
        "success": True,
        "message": "News Intelligence data retrieved successfully.",
        "data": {
            "kpis": [
                {
                    "id": 1,
                    "title": "Total News Today",
                    "value": "256",
                    "trend": "+14% from yesterday",
                    "colorClass": "blue",
                    "icon": "Radio",
                },
                {
                    "id": 2,
                    "title": "Critical News",
                    "value": "18",
                    "trend": "Requires action",
                    "colorClass": "red",
                    "icon": "AlertOctagon",
                },
                {
                    "id": 3,
                    "title": "Processing Queue",
                    "value": "12",
                    "trend": "Active ingestion",
                    "colorClass": "amber",
                    "icon": "Clock",
                },
                {
                    "id": 4,
                    "title": "Classified News",
                    "value": "244",
                    "trend": "100% parsed",
                    "colorClass": "green",
                    "icon": "CheckCircle",
                },
            ],

            "news_feed": [
                {
                    "id": 1,
                    "publisher": "Reuters Logistics",
                    "initials": "RL",
                    "headline": "Port of Mumbai Terminal 2 Faces Heavy Container Congestion",
                    "time": "5 mins ago",
                    "country": "India",
                    "state": "Maharashtra",
                    "location": "Mumbai Hub",
                    "summary": "Labor strikes and crane maintenance schedules have created a 48-hour container backlog, severely affecting outbound aggregate distributions.",
                    "entity": "JNPT Port Authority",
                    "severity": "Critical",
                    "confidence": "98%",
                    "status": "Validated",
                },
                {
                    "id": 2,
                    "publisher": "Bloomberg Supply",
                    "initials": "BS",
                    "headline": "Limestone Mining Regulations Tighten in Rajasthan",
                    "time": "12 mins ago",
                    "country": "India",
                    "state": "Rajasthan",
                    "location": "Western Block",
                    "summary": "State environmental board mandates immediate structural compliance reviews on limestone quarry crushers, slowing output rates.",
                    "entity": "Rajasthan Mines Dept",
                    "severity": "Warning",
                    "confidence": "94%",
                    "status": "Processing",
                },
                {
                    "id": 3,
                    "publisher": "JOC Logistics",
                    "initials": "JC",
                    "headline": "National Highway 48 Landslide Blocks Heavy Freight Vehicles",
                    "time": "20 mins ago",
                    "country": "India",
                    "state": "Gujarat",
                    "location": "Valsad Corridor",
                    "summary": "Monsoon flash floods trigger hillside collapse on primary logistics route. Rerouting required for all bulk cement carriers.",
                    "entity": "NHAI Highway Patrol",
                    "severity": "Critical",
                    "confidence": "99%",
                    "status": "Validated",
                },
                {
                    "id": 4,
                    "publisher": "Steel & Coal Intel",
                    "initials": "SC",
                    "headline": "Petcoke Import Tariffs Set to Rise Next Quarter",
                    "time": "35 mins ago",
                    "country": "Global",
                    "state": "All",
                    "location": "International Trade",
                    "summary": "New maritime trade policy updates suggest a 4% tariff hike on imported solid fuels, directly escalating kiln operating costs.",
                    "entity": "Ministry of Commerce",
                    "severity": "Warning",
                    "confidence": "91%",
                    "status": "Classified",
                },
                {
                    "id": 5,
                    "publisher": "Logistics Insider",
                    "initials": "LI",
                    "headline": "Silo Storage Upgrades Completed at Chennai Plant",
                    "time": "1 hr ago",
                    "country": "India",
                    "state": "Tamil Nadu",
                    "location": "Chennai South",
                    "summary": "Automated high-capacity blending systems successfully online. Local inventory buffer capacity elevated by 25% safely.",
                    "entity": "Asset Operations Edge",
                    "severity": "Safe",
                    "confidence": "97%",
                    "status": "Collected",
                },
                {
                    "id": 6,
                    "publisher": "Mint Energy",
                    "initials": "ME",
                    "headline": "Grid Voltage Fluctuation Restricts Industrial Kiln Operations",
                    "time": "2 hrs ago",
                    "country": "India",
                    "state": "Madhya Pradesh",
                    "location": "Central Grid",
                    "summary": "Substation maintenance forces localized power capping. Finished clinker grinding throughput restricted to off-peak slots.",
                    "entity": "State Electricity Board",
                    "severity": "Warning",
                    "confidence": "95%",
                    "status": "Validated",
                },
            ],

            "pipeline": [
                {
                    "id": 1,
                    "name": "Collect",
                    "status": "Active",
                    "count": "14,205 articles",
                    "time": "0.3s avg",
                    "task": "Polling 450 global feeds",
                    "active": True,
                    "icon": "Database",
                },
                {
                    "id": 2,
                    "name": "Extract",
                    "status": "Active",
                    "count": "3,110 entities",
                    "time": "0.4s avg",
                    "task": "NER text parsing engine",
                    "active": True,
                    "icon": "Search",
                },
                {
                    "id": 3,
                    "name": "Classify",
                    "status": "Active",
                    "count": "2,890 parsed",
                    "time": "0.2s avg",
                    "task": "Supply chain tag match",
                    "active": True,
                    "icon": "Layers",
                },
                {
                    "id": 4,
                    "name": "Validate",
                    "status": "Idle",
                    "count": "456 verified",
                    "time": "0.5s avg",
                    "task": "Cross-telemetry checking",
                    "active": False,
                    "icon": "CheckSquare",
                },
                {
                    "id": 5,
                    "name": "Completed",
                    "status": "Idle",
                    "count": "244 ready",
                    "time": "0.1s avg",
                    "task": "Dispatching payload logs",
                    "active": False,
                    "icon": "FileCheck",
                },
            ],

            "classified_events": [
                {
                    "id": 1,
                    "time": "13:20",
                    "type": "Port Disruption",
                    "detail": "Mumbai Port backlog confirmed via multi-source verification.",
                },
                {
                    "id": 2,
                    "time": "13:08",
                    "type": "Regulatory Change",
                    "detail": "Limestone mining caps matching operational risk markers in Rajasthan.",
                },
                {
                    "id": 3,
                    "time": "12:55",
                    "type": "Route Hazard",
                    "detail": "Landslide on NH-48 mapped to primary supply corridor.",
                },
            ],

            "status": {
                "global_regions": [
                    {
                        "name": "North America",
                        "status": "optimal",
                        "sources": "45",
                        "event": "Houston Port normal",
                        "coverage": "99.4%",
                    },
                    {
                        "name": "Europe",
                        "status": "warning",
                        "sources": "64",
                        "event": "Rhine barge low levels",
                        "coverage": "99.7%",
                    },
                    {
                        "name": "Asia Pacific",
                        "status": "critical",
                        "sources": "88",
                        "event": "Mumbai Port strike alert",
                        "coverage": "99.9%",
                    },
                ],
                "india_regions": [
                    {
                        "name": "North",
                        "status": "optimal",
                        "sources": "24",
                        "event": "NTPC supply normal",
                        "coverage": "99.1%",
                    },
                    {
                        "name": "West",
                        "status": "critical",
                        "sources": "36",
                        "event": "Landslide blocking NH-48",
                        "coverage": "99.8%",
                    },
                    {
                        "name": "East",
                        "status": "warning",
                        "sources": "22",
                        "event": "Rail allocation delay",
                        "coverage": "98.4%",
                    },
                ],
                "system_services": [
                    {
                        "name": "API Status",
                        "status": "optimal",
                    },
                    {
                        "name": "Crawler Status",
                        "status": "optimal",
                    },
                    {
                        "name": "AI Status",
                        "status": "warning",
                    },
                    {
                        "name": "Validation Engine",
                        "status": "optimal",
                    },
                ],
            },

            "analytics": {
                "most_active_sources": [
                    {
                        "source": "Reuters Logistics",
                        "articles": "74 articles",
                    },
                    {
                        "source": "Bloomberg Supply",
                        "articles": "62 articles",
                    },
                    {
                        "source": "Lloyds Maritime",
                        "articles": "48 articles",
                    },
                ],
                "refresh_metrics": {
                    "global_crawl_time": "13:24:11",
                    "polling_frequency": "180s avg",
                    "success_rate": "99.84%",
                },
                "collection_latency": {
                    "ingestion_latency": "0.34s avg",
                    "fastest_pipeline": "0.08s",
                    "slowest_edge": "1.42s",
                },
                "coverage_summary": {
                    "countries_monitored": "142 nodes",
                    "indian_states_mapped": "28 states",
                    "reliability_rating": "99.91%",
                },
            },
        },
    }